<div class="node-type-news">
  <div class="view-mode-full news-item">
    <h2>News title</h2>
    <div class="field-name-field-main-image">
      <img src="http://lorempixel.com/600/300/">
    </div>
    <div class="field-name-body">
      <p>This is a full news item, consectetur adipiscing elit. Mauris ultrices hendrerit mauris. In gravida nisl erat, vel pellentesque erat molestie ac. Donec convallis neque neque, a efficitur nunc tempus sed. Cras a posuere purus. Suspendisse et bibendum dui. Fusce varius a quam in vulputate. Nullam eget nisi sed neque feugiat pretium. Fusce porttitor leo feugiat lacinia cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc varius accumsan urna eu tristique. Nulla et bibendum mi. Nunc non sollicitudin sem, ac pharetra metus. Curabitur vel ligula volutpat, vehicula mi nec, blandit metus.This is a news teaser, consectetur adipiscing elit. Mauris ultrices hendrerit mauris. In gravida nisl erat, vel pellentesque erat molestie ac. Donec convallis neque neque, a efficitur nunc tempus sed. Cras a posuere purus. Suspendisse et bibendum dui. Fusce varius a quam in vulputate. Nullam eget nisi sed neque feugiat pretium. Fusce porttitor leo feugiat lacinia cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc varius accumsan urna eu tristique. Nulla et bibendum mi. Nunc non sollicitudin sem, ac pharetra metus. Curabitur vel ligula volutpat, vehicula mi nec, blandit metus.</p>
      <p>This is a full news item, consectetur adipiscing elit. Mauris ultrices hendrerit mauris. In gravida nisl erat, vel pellentesque erat molestie ac. Donec convallis neque neque, a efficitur nunc tempus sed. Cras a posuere purus. Suspendisse et bibendum dui. Fusce varius a quam in vulputate. Nullam eget nisi sed neque feugiat pretium. Fusce porttitor leo feugiat lacinia cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc varius accumsan urna eu tristique. Nulla et bibendum mi. Nunc non sollicitudin sem, ac pharetra metus. Curabitur vel ligula volutpat, vehicula mi nec, blandit metus.This is a news teaser, consectetur adipiscing elit. Mauris ultrices hendrerit mauris. In gravida nisl erat, vel pellentesque erat molestie ac. Donec convallis neque neque, a efficitur nunc tempus sed. Cras a posuere purus. Suspendisse et bibendum dui. Fusce varius a quam in vulputate. Nullam eget nisi sed neque feugiat pretium. Fusce porttitor leo feugiat lacinia cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc varius accumsan urna eu tristique. Nulla et bibendum mi. Nunc non sollicitudin sem, ac pharetra metus. Curabitur vel ligula volutpat, vehicula mi nec, blandit metus.</p>
    </div>
    <div class="field-name-field-main-image">
      <img src="http://lorempixel.com/600/300/">
    </div>
    <div class="field-name-body">
      <p>This is a full news item, consectetur adipiscing elit. Mauris ultrices hendrerit mauris. In gravida nisl erat, vel pellentesque erat molestie ac. Donec convallis neque neque, a efficitur nunc tempus sed. Cras a posuere purus. Suspendisse et bibendum dui. Fusce varius a quam in vulputate. Nullam eget nisi sed neque feugiat pretium. Fusce porttitor leo feugiat lacinia cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc varius accumsan urna eu tristique. Nulla et bibendum mi. Nunc non sollicitudin sem, ac pharetra metus. Curabitur vel ligula volutpat, vehicula mi nec, blandit metus.This is a news teaser, consectetur adipiscing elit. Mauris ultrices hendrerit mauris. In gravida nisl erat, vel pellentesque erat molestie ac. Donec convallis neque neque, a efficitur nunc tempus sed. Cras a posuere purus. Suspendisse et bibendum dui. Fusce varius a quam in vulputate. Nullam eget nisi sed neque feugiat pretium. Fusce porttitor leo feugiat lacinia cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc varius accumsan urna eu tristique. Nulla et bibendum mi. Nunc non sollicitudin sem, ac pharetra metus. Curabitur vel ligula volutpat, vehicula mi nec, blandit metus.</p>
      <p>This is a full news item, consectetur adipiscing elit. Mauris ultrices hendrerit mauris. In gravida nisl erat, vel pellentesque erat molestie ac. Donec convallis neque neque, a efficitur nunc tempus sed. Cras a posuere purus. Suspendisse et bibendum dui. Fusce varius a quam in vulputate. Nullam eget nisi sed neque feugiat pretium. Fusce porttitor leo feugiat lacinia cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc varius accumsan urna eu tristique. Nulla et bibendum mi. Nunc non sollicitudin sem, ac pharetra metus. Curabitur vel ligula volutpat, vehicula mi nec, blandit metus.This is a news teaser, consectetur adipiscing elit. Mauris ultrices hendrerit mauris. In gravida nisl erat, vel pellentesque erat molestie ac. Donec convallis neque neque, a efficitur nunc tempus sed. Cras a posuere purus. Suspendisse et bibendum dui. Fusce varius a quam in vulputate. Nullam eget nisi sed neque feugiat pretium. Fusce porttitor leo feugiat lacinia cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc varius accumsan urna eu tristique. Nulla et bibendum mi. Nunc non sollicitudin sem, ac pharetra metus. Curabitur vel ligula volutpat, vehicula mi nec, blandit metus.</p>
    </div>
  </div>
</div>
